routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\HalamanUtamaController;
use App\Http\Controllers\LayananController;
use App\Http\Controllers\DetailsLayananController;
use App\Http\Controllers\ObjekWisataController;
use App\Http\Controllers\AuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::resource('posts', PostController::class);

Route::get('/', function () {
    return view('welcome');
});


Route::get('/dashboard', [HalamanUtamaController::class, 'dashboard'])->middleware('auth');
Route::get('logout', [AuthController::class, 'logout']);
Route::get('/', [HalamanUtamaController::class, 'index']);
Route::get('contact', [HalamanUtamaController::class, 'contact']);

// halaman tentang
Route::get('/sejarah', [HalamanUtamaController::class, 'sejarah']);
Route::get('/arti-lambang', [HalamanUtamaController::class, 'arti_lambang']);
// Route::get('layouts', [HalamanUtamaController::class, 'index_layout']);

// halaman layanan
Route::get('layanans/{id}/{layanan}', [HalamanUtamaController::class, 'index_layanan']);
Route::get('layanans/{id}/{layanan}/{slug}', [HalamanUtamaController::class, 'show_details_layanan']);
Route::resource('layanan', LayananController::class)->middleware('auth');
Route::resource('details-layanan', DetailsLayananController::class)->middleware('auth');
// Route::resource('objek-wisata', ObjekWisataController::class);

Auth::routes();


// Route::get('layanan/keamanan ', [HalamanUtamaController::class, 'index_keamanan']);
// Route::get('layanan/keamanan/{title} ', [HalamanUtamaController::class, 'show_keamanan']);
   
//halaman dashboard
// Route::get('/kesehatan/create', [HalamanUtamaController::class, 'create'])->middleware('password.confirm');

// Route::resource('keamanan', KeamananController::class)->middleware('auth');
// Route::resource('kesehatan', KesehatanController::class)->middleware('auth');
// Route::resource('transport', TransportController::class)->middleware('auth');
// Route::resource('pemadam-kebakaran',Pemadam_kebakaranController::class)->middleware('auth');
// Route::resource('lingkungan-hidup', Lingkungan_hidupController::class)->middleware('auth');
// Route::resource('olahraga', OlahragaController::class)->middleware('auth');


// Route::get('upload-image', [UploadImageController::class, 'index']);
// Route::post('save', [UploadImageController::class, 'save']);


// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Layanan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Layanan extends Model
{
    use HasFactory;
    protected $table = 'layanan';
    protected $fillable = ['nama','slug','icon','color'];
    public function detailsLayanan()
    {
        return $this->hasMany(DetailsLayanan::class,'layanan_id');
    }
    public function objekWisata()
    {
        return $this->hasMany(ObjekWisata::class,'layanan_id');
    }
}

app/Http/Controllers/LayananController.php
<?php
 
namespace App\Http\Controllers;
use Illuminate\Support\Str;
 
use Illuminate\Http\Request;
use App\Models\Layanan;
  
class LayananController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('password.confirm')->only(['create']);
        // $this->middleware('password.confirm')->only(['show']);
        $this->middleware('password.confirm')->only(['edit']);

    }

    public function index()
    {
        /// mengambil data terakhir dan pagination 5 list
        $Layanans = Layanan::get();
        // dd($Layanans);
        /// mengirimkan variabel $Layanans ke halaman views Layanans/index.blade.php
        /// include dengan number index
        return view('layananDashboard.Layanans.index', compact('Layanans'));
            // ->with('i', (request()->input('page', 1) - 1) * 5);
    }
  
    public function create()
    {
        /// menampilkan halaman create
        return view('layananDashboard.Layanans.create');
    }
  
    public function store(Request $request)
    {
        /// membuat validasi untuk title dan content wajib diisi
        $request->validate([
            'nama' => 'required|unique:layanan,nama',
            'icon' => 'required|unique:layanan,icon',
        ]);
        
        $slug = Str::slug($request->nama, '-');
        $request['slug'] = $slug;
        // dd($request->all());
        /// insert setiap request dari form ke dalam database via model
        /// jika menggunakan metode ini, maka nama field dan nama form harus sama
        Layanan::create($request->all());
        
         
        /// redirect jika sukses menyimpan data
        return redirect()->route('layanan.index')
                        ->with('success','Layanan created successfully.');
    }
  
    public function show(Layanan $layanan)
    {
        /// dengan menggunakan resource, kita bisa memanfaatkan model sebagai parameter
        /// berdasarkan id yang dipilih
        /// href="{{ route('Layanans.show',$post->id) }}
        return view('layananDashboard.Layanans.show',compact('layanan'));
    }
  
    public function edit(Layanan $layanan)
    {
        /// dengan menggunakan resource, kita bisa memanfaatkan model sebagai parameter
        /// berdasarkan id yang dipilih
        /// href="{{ route('Layanans.edit',$post->id) }}
        return view('layananDashboard.Layanans.edit',compact('layanan'));
    }
  
    public function update(Request $request, Layanan $Layanan)
    {
        /// membuat validasi untuk title dan content wajib diisi
        // $request->validate([
        //     'title' => 'required',
        //     'content' => 'required',
        // ]);
         
        /// mengubah data berdasarkan request dan parameter yang dikirimkan
        $Layanan->update($request->all());
         
        /// setelah berhasil mengubah data
        return redirect()->route('layanan.index')->with('success','Layanan updated successfully');
    }
  
    public function destroy(Layanan $layanan)
    {
        /// melakukan hapus data berdasarkan parameter yang dikirimkan
        $layanan->delete();
  
        return redirect()->route('layanan.index')
                        ->with('success','Layanan deleted successfully');
    }
}

resources/views/layananDashboard/Layanans/index.blade.php
@extends('layoutsDashboard.index') 
@section('content')
 
 
  <!-- Begin Page Content -->
  <div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Tables Layanan</h1>
<p class="mb-4"></p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6> -->

        <div class="float-right"  style="margin-buttom:100px"  >
            <a class="btn btn-success" href="{{ route('layanan.create') }}"> Create Post</a>
        </div>
    </div>
    
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>title</th>
                        <th style="text-align:center; width:20%" >action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>title</th>
                        <th style="text-align:center; width:20%" >action</th>
                    </tr>
                </tfoot>
                <tbody>
                @foreach ($Layanans as $layanan)
                    <tr>
                        <td> {{$layanan->nama}} </td>
                        <td class="text-center">
                            <form action="{{ route('layanan.destroy',$layanan->id) }}" method="POST">
                                <a class="btn btn-info btn-sm" href="{{ route('layanan.show',$layanan->id) }} ">Show  </a>
                                <a class="btn btn-primary btn-sm" href="{{ route('layanan.edit',$layanan ->id) }}">Edit</a>         
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                            </form>
                        </td>
                        
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->

@endsection

resources/views/layananDashboard/Layanans/show.blade.php
@extends('layoutsDashboard.index')
 
@section('content')

 <!-- Begin Page Content -->
 <div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">layanan post</h1>
<p class="mb-4"></p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6> -->

        
    </div>
    
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               
            <div class="row mt-5 mb-5">
            <div class="col-lg-12 margin-tb">
                <div class="float-left">
                    <h2>Create New Post</h2>
                </div>
                <div class="float-right">
                    <a class="btn btn-secondary" href="{{ route('layanan.index') }}"> Back</a>
                </div>
            </div>
        </div>
        
        <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama:</strong>
                {{ $layanan->nama }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Slug:</strong>
                {{ $layanan->slug }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Icon:</strong>
                {{ $layanan->icon }}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Color:</strong>
                @php
                    echo $layanan->color
                @endphp
            </div>
        </div>
    </div>
            </table>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->


        


@endsection