routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\HalamanUtamaController;
use App\Http\Controllers\LayananController;
use App\Http\Controllers\DetailsLayananController;
use App\Http\Controllers\ObjekWisataController;
use App\Http\Controllers\AuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::resource('posts', PostController::class);

Route::get('/', function () {
    return view('welcome');
});


Route::get('/dashboard', [HalamanUtamaController::class, 'dashboard'])->middleware('auth');
Route::get('logout', [AuthController::class, 'logout']);
Route::get('/', [HalamanUtamaController::class, 'index']);
Route::get('contact', [HalamanUtamaController::class, 'contact']);

// halaman tentang
Route::get('/sejarah', [HalamanUtamaController::class, 'sejarah']);
Route::get('/arti-lambang', [HalamanUtamaController::class, 'arti_lambang']);
// Route::get('layouts', [HalamanUtamaController::class, 'index_layout']);

// halaman layanan
Route::get('layanans/{id}/{layanan}', [HalamanUtamaController::class, 'index_layanan']);
Route::get('layanans/{id}/{layanan}/{slug}', [HalamanUtamaController::class, 'show_details_layanan']);
Route::resource('layanan', LayananController::class)->middleware('auth');
Route::resource('details-layanan', DetailsLayananController::class)->middleware('auth');
// Route::resource('objek-wisata', ObjekWisataController::class);

Auth::routes();


// Route::get('layanan/keamanan ', [HalamanUtamaController::class, 'index_keamanan']);
// Route::get('layanan/keamanan/{title} ', [HalamanUtamaController::class, 'show_keamanan']);
   
//halaman dashboard
// Route::get('/kesehatan/create', [HalamanUtamaController::class, 'create'])->middleware('password.confirm');

// Route::resource('keamanan', KeamananController::class)->middleware('auth');
// Route::resource('kesehatan', KesehatanController::class)->middleware('auth');
// Route::resource('transport', TransportController::class)->middleware('auth');
// Route::resource('pemadam-kebakaran',Pemadam_kebakaranController::class)->middleware('auth');
// Route::resource('lingkungan-hidup', Lingkungan_hidupController::class)->middleware('auth');
// Route::resource('olahraga', OlahragaController::class)->middleware('auth');


// Route::get('upload-image', [UploadImageController::class, 'index']);
// Route::post('save', [UploadImageController::class, 'save']);


// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/DetailsLayanan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DetailsLayanan extends Model
{
    use HasFactory;
    protected $table = 'details_layanan';
    protected $fillable= ['layanan_id','image','title','subtitle','details','slug'];

    public function layanan()
    {
        return $this->belongsTo(Layanan::class,'layanan_id');
    }
}

app/Http/Controllers/DetailsLayananController.php
<?php
 
namespace App\Http\Controllers;
use Illuminate\Support\Str;

use Illuminate\Http\Request;
use App\Models\DetailsLayanan;
use App\Models\Layanan;
use Image;
  
class DetailsLayananController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('password.confirm')->only(['create']);
        // $this->middleware('password.confirm')->only(['show']);
        $this->middleware('password.confirm')->only(['edit']);

    }

    public function index()
    {
        /// mengambil data terakhir dan pagination 5 list
        $DetailsLayanans = DetailsLayanan::with("layanan")->get();
        // $Layanans = Layanan::get();
        // dd($Layanans);
        /// mengirimkan variabel $DetailsLayanans ke halaman views DetailsLayanans/index.blade.php
        /// include dengan number index
        return view('layananDashboard.DetailsLayanans.index', compact('DetailsLayanans'));
            // ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        /// menampilkan halaman create
        $Layanans = Layanan::get();

        return view('layananDashboard.DetailsLayanans.create',compact('Layanans'));
    }
  
    public function store(Request $request)
    {
        // dd($request->all());
        $request->validate([
            'title' => 'required',
            'subtitle' => 'required',
            'details' => 'required',
            'image' => 'required',
        ]);
        $slug = Str::slug($request->title, '-');
        $request['slug'] = $slug;
        

        if ($request->file('image')) {
            $image = $request->file('image');

            $file_name = time(). rand(1111, 9999) . '.' .$image->getClientOriginalExtension();

            // $save_Path = 'images/'.$file_name;
            //$save_Path = public_path('images/'.$file_name);

            //Image::make($image->getRealPath())->resize(300, 236)->save($save_Path);
            $image->move('images',$file_name);
            Image::make('images/'.$file_name)->save('images/'.$file_name);
        } else {
            $file_name = null;
        }

     
        $data = new DetailsLayanan;
		$data->title = $request->title;
		$data->slug = $slug;
        $data->subtitle = $request->subtitle;
		$data->details = $request->details;
        $data->layanan_id = $request->layanan_id;
        $data->image = $file_name;

        $data->save();

        //request()->pic->move(public_path('assets/images'), $imageName);
        //return redirect('akuntansi');
        return redirect()->route('details-layanan.index')
                        ->with('success','DetailsLayanan created successfully.');
    }
  
    public function show(DetailsLayanan $detailsLayanan)
    {
        /// dengan menggunakan resource, kita bisa memanfaatkan model sebagai parameter
        /// berdasarkan id yang dipilih
        /// href="{{ route('DetailsLayanans.show',$post->id) }}
        // dd($detailsLayanan);
        return view('layananDashboard.DetailsLayanans.show',compact('detailsLayanan'));
    }
  
    public function edit( DetailsLayanan $detailsLayanan)
    {
        /// dengan menggunakan resource, kita bisa memanfaatkan model sebagai parameter
        /// berdasarkan id yang dipilih
        /// href="{{ route('DetailsLayanans.edit',$post->id) }}
        return view('layananDashboard.DetailsLayanans.edit',compact('detailsLayanan'));
    }
  
    public function update(Request $request, DetailsLayanan $DetailsLayanan)
    {
        
        $slug = Str::slug($request->title, '-');
        $request['slug_details'] = $slug;
        
        $id = $request->input('id');
        $data = DetailsLayanan::findorfail($id);
        

        if ($request->file('image')){

            $image = $request->file("image");

            $file_name = time(). rand(1111, 9999) . '.' .$image->getClientOriginalExtension();

            $image->move('images',$file_name);
            Image::make('images/'.$file_name)->save('images/'.$file_name);

        }
        elseif($data->image != null){
            $file_name = $request->input('image');
        }
        else{
            $file_name = null;
        }

        $data->title = $request->title;
		$data->slug_details = $slug;
        $data->subtitle = $request->subtitle;
		$data->details = $request->details;
        $data->layanan_id = $request->layanan_id;
        $data->image = $file_name;
        $data->update();
        
        /// membuat validasi untuk title dan content wajib diisi
        // $request->validate([
        //     'title' => 'required',
        //     'content' => 'required',
        // ]);
         
        /// mengubah data berdasarkan request dan parameter yang dikirimkan
        // $DetailsLayanan->update($request->all());
        
        /// setelah berhasil mengubah data
        return redirect()->route('details-layanan.index')->with('success','DetailsLayanan updated successfully');
    }
  
    public function destroy(DetailsLayanan $detailsLayanan)
    {
        /// melakukan hapus data berdasarkan parameter yang dikirimkan
        $detailsLayanan->delete();
  
        return redirect()->route('details-layanan.index')
                        ->with('success','DetailsLayanan deleted successfully');
    }
}

resources/views/layananDashboard/DetailsLayanans/create.blade.php
@extends('layoutsDashboard.index')
 
@section('content')

 <!-- Begin Page Content -->
 <div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Layanan</h1>
<p class="mb-4"></p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6> -->

        
    </div>
    
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               
            <div class="row mt-5 mb-5">
            <div class="col-lg-12 margin-tb">
                <div class="float-left">
                    <h2>Create details Layanan</h2>
                </div>
                <div class="float-right">
                    <a class="btn btn-secondary" href="{{ route('details-layanan.index') }}"> Back</a>
                </div>
            </div>
        </div>
        
        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
        <form action="{{ route('details-layanan.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group row">
                <strong class="col-lg-2 form-control-label">Layanan:</strong>
                <div class="col-lg-3">
                    <select name="layanan_id" id="layanan_id" class="form-control select" required>
                    <option value="">-- PILIH layanan --</option>
                    @foreach ($Layanans as $layanan)
                    <option value="{{ $layanan->id }}">{{ $layanan->nama}}</option>
                    @endforeach
                    </select>
                    </div>
                </div>

            <div class="row">
                
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Title:</strong>
                        {{-- @error('title') --}}
                            <input type="text" name="title" class="form-control" placeholder="Title" required>
                        {{-- @enderror --}}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Subtitle:</strong>
                        {{-- @error('subtitle') --}}
                            <input type="text" name="subtitle" class="form-control" placeholder="Subtitle" required>
                        {{-- @enderror --}}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <input type="file" name="image" placeholder="Choose image" id="image">
                        @error('image')
                            <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror
                      </div>
                </div>
                <script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
                <script type="text/javascript">
                    $(document).ready(function () {
                        $('.ckeditor').ckeditor();
                    });
                </script>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>details:</strong>
                        <br>
                        <textarea class="ckeditor" name="details" placeholder="details" required></textarea>
                    </div>
                </div>
                
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        
        </form>
            </table>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->


        


@endsection

resources/views/layananDashboard/DetailsLayanans/edit.blade.php
@extends('layoutsDashboard.index')
 
@section('content')

<style>
    input[type="file"]{
    color: transparent;
    }
</style>

 <!-- Begin Page Content -->
 <div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Keamanan post</h1>
<p class="mb-4"></p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6> -->

        
    </div>
    
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               
            <div class="row mt-5 mb-5">
            <div class="col-lg-12 margin-tb">
                <div class="float-left">
                    <h2>Create New Post</h2>
                </div>
                <div class="float-right">
                    <a class="btn btn-secondary" href="{{ route('details-layanan.index') }}"> Back</a>
                </div>
            </div>
        </div>
        
        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    
        <form action="{{ route('details-layanan.update',$detailsLayanan->id) }}" method="POST" enctype="multipart/form-data"n>
            @csrf
            @method('PUT')
            <div class="row">
                {{-- @if($detailsLayanan->image == null)
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <input type="file" value="{{$detailsLayanan->image}}" name="image" placeholder="image" id="image">
                        {{-- @error('image')
                            <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror --}}
                      {{-- </div>
                </div>
                @else --}}
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <input type="hidden" value="{{$detailsLayanan->id}}" name="id" >
                        <input type="hidden" value="{{$detailsLayanan->image}}" name="image">
                        <input type="hidden" value="{{$detailsLayanan->layanan_id}}" name="layanan_id">

                        <img src="{{url('images')}}/{{$detailsLayanan->image}}" style="width:70px"><br>
                        <input style="padding:0px" type="file" value="{{$detailsLayanan->image}}" name="image" placeholder="{{$detailsLayanan->image}}" id="image">
                        {{-- <p>{{$detailsLayanan->image}}"</p> --}}
                        {{-- @error('image')
                            <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                        @enderror --}}
                      </div>
                </div>
                {{-- @endif --}}
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Title:</strong>
                        <input type="text" name="title" value="{{ $detailsLayanan->title }}" class="form-control" placeholder="Title">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>subtitle:</strong>
                        <input type="text" name="subtitle" value="{{ $detailsLayanan->subtitle }}"  class="form-control" placeholder="subtitle">
                    </div>
                </div>
                <script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
                <script type="text/javascript">
                    $(document).ready(function () {
                        $('.ckeditor').ckeditor();
                    });
                </script>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>details:</strong>
                        <br>
                        <textarea class="ckeditor" name="details" placeholder="details">{{ $detailsLayanan->details }}</textarea>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">update</button>
                </div>
            </div>
        
        </form>
            </table>
        </div>
    </div>
</div>

</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script>
$(function () {
    $('input[type="file"]').change(function () {
         if ($(this).val() != "") {
                $(this).css('color', '#333');
         }else{
                $(this).css('color', 'transparent');
         }
    });
})
</script>

<!-- /.container-fluid -->


        


@endsection

resources/views/layananDashboard/DetailsLayanans/index.blade.php
@extends('layoutsDashboard.index') 
@section('content')
 
 
  <!-- Begin Page Content -->
  <div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Tables Details Layanan</h1>
<p class="mb-4"></p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6> -->

        <div class="float-right"  style="margin-buttom:100px"  >
            <a class="btn btn-success" href="{{ route('details-layanan.create') }}"> Create Post</a>
        </div>
    </div>
    
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th style="text-align:center; width:15%" >layanan</th>
                        <th style="text-align:center; width:20%" >action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Title</th>
                        <th style="text-align:center; width:15%" >layanan</th>
                        <th style="text-align:center; width:20%" >action</th>
                    </tr>
                </tfoot>
                <tbody>
                @foreach ($DetailsLayanans as $DetailsLayanan)
                    <tr>
                        <td>{{$DetailsLayanan->title}}</td>
                        <td style="text-align:center" >{{$DetailsLayanan->layanan->nama}}</td>
                        <td class="text-center">
                            <form action="{{ route('details-layanan.destroy',$DetailsLayanan->id) }}" method="POST">
                                <a class="btn btn-info btn-sm" href="{{ route('details-layanan.show',$DetailsLayanan->id)}}">Info Detail</a>
                                <a class="btn btn-primary btn-sm" href="{{ route('details-layanan.edit',$DetailsLayanan->id) }}">Edit</a>         
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->

@endsection

resources/views/layananDashboard/DetailsLayanans/show.blade.php
@extends('layoutsDashboard.index')
 
@section('content')
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

 <!-- Begin Page Content -->
 <div class="container-fluid">

<!-- Page Heading -->
{{-- <h1 class="h3 mb-2 text-gray-800">Info Details</h1> --}}
<p class="mb-4"></p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6> -->

        
    </div>
    
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               
            <div class="row mt-5 mb-5">
            <div class="col-lg-12 margin-tb">
                <div class="float-left">
                    <h2>Info Details</h2>
                </div>
                <div class="float-right">
                    <a class="btn btn-secondary" href="{{ route('details-layanan.index') }}"> Back</a>
                </div>
            </div>
        </div>
        
        <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Image:</strong> 
                <br>
                <img src="{{url('images')}}/{{$detailsLayanan->image}}" style="width:50%" class="rounded float-left" alt="">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong> 
                <br>
                {{ $detailsLayanan->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Subtitle:</strong> 
                <br>
                {{ $detailsLayanan->subtitle }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Content:</strong>
                @php
                    echo $detailsLayanan->details
                @endphp
            </div>
        </div>
    </div>
            </table>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->


        


@endsection